language: php

services:
  - docker

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php src/index.php coucou
  - php src/index.php hello

jobs:
  include:
    - stage: build docker image
      if: tag IS present
      php: 7.3
      env: COMPOSER_FLAGS=""
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export REPO=$DOCKER_USERNAME/sandbox
        - docker build -f docker/Dockerfile -t $REPO:$TRAVIS_TAG .
        - docker tag $REPO:$TRAVIS_TAG $REPO:latest
        - docker push $REPO
