language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php src/index.php coucou


jobs:
  include:
    - stage: build docker image
      if: branch = master AND type = push
      php: 7.3
      env: COMPOSER_FLAGS=""
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export REPO=$DOCKER_USERNAME/sandbox
        - docker build -f docker/Dockerfile -t $REPO:latest .
        #- docker tag $REPO:$TRAVIS_TAG $REPO:latest
        - docker push $REPO
