name: Docker
on:
  # We try to build image on each PR.
  pull_request: ~
  # When tagged, we also push the image to the docker registry.
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker image build
    env:
      publish: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
        if: ${{ env.publish == 'true' }}
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin
        if: ${{ env.publish == 'true' }}
      - name: Build image
        run: docker build -f docker/Dockerfile -t jibbarth/sandbox:latest .
      - name: Tag image
        run: |
          docker tag jibbarth/sandbox:latest jibbarth/sandbox:${{ env.RELEASE_VERSION }}
        if: ${{ env.publish == 'true' }}
      - name: Push image to hub.docker.com registry
        run: docker push jibbarth/sandbox
        if: ${{ env.publish == 'true' }}
