name: Docker

on:
  pull_request: ~
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker image build
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          repository: ${{ github.repository }}
          tag_with_ref: true
          push: ${{ github.event_name == 'push' }}
